// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNCN8cYwr4gSfbbbEqTfnOYwRcJbM7_w',
    appId: '1:729768757138:web:4ce3b23600ff4de272e34b',
    messagingSenderId: '729768757138',
    projectId: 'vivarium-soocho',
    authDomain: 'vivarium-soocho.firebaseapp.com',
    databaseURL: 'https://vivarium-soocho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vivarium-soocho.appspot.com',
    measurementId: 'G-9C0DEJPCH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jU9TNwxC0KIDGwssNLLPOHM23r8fpJg',
    appId: '1:729768757138:android:d487c5565dbe1e9172e34b',
    messagingSenderId: '729768757138',
    projectId: 'vivarium-soocho',
    databaseURL: 'https://vivarium-soocho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vivarium-soocho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCViwQC-DHGBsAxprU6b7ngv3EokbdnsIo',
    appId: '1:729768757138:ios:79b1d9f94bee71d372e34b',
    messagingSenderId: '729768757138',
    projectId: 'vivarium-soocho',
    databaseURL: 'https://vivarium-soocho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vivarium-soocho.appspot.com',
    iosBundleId: 'com.example.vivarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCViwQC-DHGBsAxprU6b7ngv3EokbdnsIo',
    appId: '1:729768757138:ios:fd1b4eb3bfd5ca3572e34b',
    messagingSenderId: '729768757138',
    projectId: 'vivarium-soocho',
    databaseURL: 'https://vivarium-soocho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vivarium-soocho.appspot.com',
    iosBundleId: 'com.example.vivarium.RunnerTests',
  );
}
